### ISSUE TITLE
invalid import 'tree_sitter_jai_external_scanner_create'

### ISSUE THREAD

**Issue by NickTsaizer** [St0wy/zed-jai#1]
The syntax is correct, but LS is failed to start and i have this message in logs:

2024-08-07T22:02:22.3894238+03:00 [ERROR] failed to load language Jai:
Failed to instantiate wasm module: invalid import 'tree_sitter_jai_external_scanner_create'

**Comment by St0wy** [comment]
I don't think the issue is related to the language server (if that is what you mean by LS) since I haven't added it yet. This extension just has basic (and wrong for now) syntax highlighting.

What version of Zed do you have and on what OS are you on ?

**Comment by NickTsaizer** [comment]
Oh, yeh, my bad, i thought you used jails, idk why. I am using Windows and this version..? Commit? 

https://github.com/zed-industries/zed/tree/6f6eeb65954bb96954522deb330e40b746075ba6
